- kind: Message
  name: VideoSettings
  fields:
  - name: volume # 0 to 10
    type: number
    index: 1
  - name: preferredAudioName
    type: string
    index: 2
  - name: playbackSpeed # .25x to 4x
    type: number
    index: 3
  - name: preferredSubtitleName
    type: string
    index: 4
- kind: Enum
  name: StackingMethod
  values:
  - name: RANDOM
    value: 1
  - name: TOP_DOWN
    value: 2
- kind: Message
  name: DanmakuOverlaySettings
  fields:
  - name: speed
    type: number
    index: 1
  - name: density # 0 to 100 percentage, meaning for every 100 pixels, the number of pixels should be occupied.
    type: number
    index: 2
  - name: stackingMethod
    type: StackingMethod
    index: 3
- kind: Enum
  name: ChatOverlayStyle
  values:
  - name: NONE
    value: 1
  - name: SIDE
    value: 2
  - name: DANMAKU
    value: 3
- kind: Message
  name: ChatOverlaySettings
  fields:
  - name: style
    type: ChatOverlayStyle
    index: 1
  - name: opacity # 0 to 100 percentage
    type: number
    index: 2
  - name: fontSize
    type: number
    index: 3
  - name: danmakuSettings
    type: DanmakuOverlaySettings
    index: 4
- kind: Message
  name: VideoPlayerSettings
  fields:
  - name: videoSettings
    type: VideoSettings
    index: 1
  - name: chatOverlaySettings
    type: ChatOverlaySettings
    index: 2
